on:
  workflow_dispatch: ~
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/excavator.yml"
  schedule:
    - cron: "0 */4 * * *"
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
